name: Branch

on:
  push:
    branches-ignore: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Build For Windows
        run: GOOS=windows go build -o bin/csv-splitter.exe .

      - name: Build For Unix
        run: go build -o bin/csv-splitter .
      
      - name: Test
        run: go test -v ./...

      - name: Build Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            LICENSE.md
            executables.zip
          draft: true
          tag_name: build-${{ github.sha }}
