name: Branch

on:
  push:
    branches-ignore: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Build For Windows
        run: GOOS=windows go build -o bin/csv-splitter.exe .

      - name: Build For Unix
        run: go build -o bin/csv-splitter .
      
      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic
        
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      
      - uses: vimtor/action-zip@v1
        with:
          files: bin
          dest: executables.zip

      - name: Build Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            LICENSE.md
            executables.zip
          draft: true
          tag_name: build-${{ github.sha }}
