name: Branch

on:
  push:
    branches-ignore: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Build
        run: go build -v .
      
      - name: Test
        run: go test -v ./...
