name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Build For Windows
        run: GOOS=windows go build -o bin/csv-parser.exe .

      - name: Build For Unix
        run: go build -o bin/csv-parser .
      
      - name: Test
        run: go test -v ./...

      - name: Save Release SHA
        run: echo ${{ github.sha }} > Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            LICENSE.md
            bin/csv-splitter
            bin/csv-splitter.exe