name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        ref: 'master'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Build
        run: go build -v .
      
      - name: Test
        run: go test -v ./...

      - name: Save Release SHA
        run: echo ${{ github.sha }} > Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            LICENSE.md
            csv-splitter